app.name=SĀTHI
app.tagline=Your Private AI Companion
spring.application.name=savan-server
server.port=8080
server.address=0.0.0.0

 # LAPTOP_URL = http://10.153.210.18:8080/transcripts

# Ollama Properties
spring.ai.ollama.base-url=http://localhost:11434/
spring.ai.ollama.chat.options.model=gemma:2b
spring.ai.ollama.chat.options.temperature=0.7

logging.level.org.springframework.ai.chat.client.advisor= DEBUG
logging.level.org.stg.savan.savanserver.service.impl.TranscriptServiceImpl=${SATHI_RETRIEVAL_LOG_LEVEL:INFO}


spring.datasource.url=jdbc:postgresql://localhost:5433/sathi
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.initialize-schema=true
